---
- name: "include sub_datasets vars from {{ from }}"
  include_vars:
    file: "sub_datasets_{{ from }}.yml"

- name: "get associated dataset for {{ parent_mountpoint }}"
  shell: zfs list -H "{{ parent_mountpoint }}" | awk '{print $1}'
  register: parent_dataset
  changed_when: False

- name: "check parent_dataset uniqueness"
  fail:
    msg: "parent_dataset is not unique: {{ parent_dataset.stdout }}"
  when: (parent_dataset.stdout_lines | length) > 1

- name: "get root dataset for {{ parent_dataset }}"
  shell: echo "{{ parent_dataset.stdout }}" | cut -d/ -f1
  register: root_dataset
  changed_when: False
  when: root_pool is defined and root_pool and parent_dataset.stdout != ""

- block:
    - set_fact:
        ref_dataset: "{{ root_dataset.stdout | default(parent_dataset.stdout) }}"

    - include_tasks: dataset.yml
      vars:
        dataset_parent: "{{ ref_dataset }}"
      loop: "{{ sub_datasets }}"
      loop_control:
        loop_var: dataset

  when: parent_dataset.stdout != ""
