---
- name: "check if {{ zpool }} exists"
  shell: "zfs list {{ zpool }}"
  register: zpool_status
  changed_when: False
  ignore_errors: yes

- block:
    - name: "load {{ zpool }} config"
      include_vars:
        file: "{{ zpool }}.yml"

    - name: "set {{ zpool }} pool properties"
      zfs:
        name: "{{ zpool }}"
        state: present
        extra_zfs_properties: "{{ zpool_properties }}"

    - include: dataset.yml dataset_parent="{{ zpool }}" dataset="{{ dataset_i }}"
      loop: "{{ datasets }}"
      loop_control:
        loop_var: dataset_i

  when: zpool_status.rc == 0
